config/routes.rb
Reflib::Application.routes.draw do
  resources :topics

  resources :references

  root :to => "references#index"

end

app/models/reference.rb
class Reference < ActiveRecord::Base
	# Every Reference has a Topic
	belongs_to :topic

	attr_accessible :description, :name, :topic_id, :tag_list, :doc

	# Verify that we've got data where we need it
	validates_presence_of :name, :topic_id

  # Taggable!
  acts_as_taggable

  # CarrierWave Uploader
  mount_uploader :doc, DocUploader

end

app/models/topic.rb
class Topic < ActiveRecord::Base
	# Every Topic is associated with multiple References
	has_many :references

  attr_accessible :name

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/references_controller.rb
class ReferencesController < ApplicationController
  # GET /references
  # GET /references.json
  def index
    @references = Reference.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @references }
    end
  end

  # GET /references/1
  # GET /references/1.json
  def show
    @reference = Reference.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @reference }
    end
  end

  # GET /references/new
  # GET /references/new.json
  def new
    @reference = Reference.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @reference }
    end
  end

  # GET /references/1/edit
  def edit
    @reference = Reference.find(params[:id])
  end

  # POST /references
  # POST /references.json
  def create
    @reference = Reference.new(params[:reference])

    respond_to do |format|
      if @reference.save
        format.html { redirect_to @reference, notice: 'Reference was successfully created.' }
        format.json { render json: @reference, status: :created, location: @reference }
      else
        format.html { render action: "new" }
        format.json { render json: @reference.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /references/1
  # PUT /references/1.json
  def update
    @reference = Reference.find(params[:id])

    respond_to do |format|
      if @reference.update_attributes(params[:reference])
        format.html { redirect_to @reference, notice: 'Reference was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @reference.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /references/1
  # DELETE /references/1.json
  def destroy
    @reference = Reference.find(params[:id])
    @reference.destroy

    respond_to do |format|
      format.html { redirect_to references_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @topics }
    end
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
    @topic = Topic.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @topic }
    end
  end

  # GET /topics/new
  # GET /topics/new.json
  def new
    @topic = Topic.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @topic }
    end
  end

  # GET /topics/1/edit
  def edit
    @topic = Topic.find(params[:id])
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(params[:topic])

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render json: @topic, status: :created, location: @topic }
      else
        format.html { render action: "new" }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /topics/1
  # PUT /topics/1.json
  def update
    @topic = Topic.find(params[:id])

    respond_to do |format|
      if @topic.update_attributes(params[:topic])
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy

    respond_to do |format|
      format.html { redirect_to topics_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/references_helper.rb
module ReferencesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reflib</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
		<%= yield %>
	</div>
</body>
</html>

app/views/references/_form.html.erb
<%= form_for @reference, :html => {:multipart => true} do |f| %>
  <% if @reference.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reference.errors.count, "error") %> prohibited this reference from being saved:</h2>

      <ul>
      <% @reference.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>

   <div class="field">
    <%= f.label :topic_id, "Topic" %><br />
    <%= f.select(:topic_id, options_for_select( Topic.order("name ASC").map {|t| [t.name,t.id] }, @reference.topic )) %>

  </div>

  <div class="field">
    <%= f.label :doc, "Reference Document File Upload" %><br />
    <%= f.file_field :doc %>
  </div>

  <div class="field">
    <%= f.label :tag_list, "Tags (in a comma-separated list)" %><br />
    <%= f.text_field :tag_list %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>

  
<% end %>

app/views/references/edit.html.erb
<h1>Editing reference</h1>

<%= render 'form' %>

<%= link_to 'Show', @reference %> |
<%= link_to 'Back', references_path %>

app/views/references/index.html.erb
<h1>Listing references</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Topic</th>
    <th>Tags</th>
    <th>Doc</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @references.each do |reference| %>
  <tr>
    <td><%= reference.name %></td>
    <td><%= reference.description %></td>
    <td><%= reference.topic.name %></td>
    <td><%= reference.tag_list %></td>
    <td><%= link_to 'File', reference.doc_url %></td>
    <td><%= link_to 'Show', reference %></td>
    <td><%= link_to 'Edit', edit_reference_path(reference) %></td>
    <td><%= link_to 'Destroy', reference, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Reference', new_reference_path %>

app/views/references/new.html.erb
<h1>New reference</h1>

<%= render 'form' %>

<%= link_to 'Back', references_path %>

app/views/references/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @reference.name %>
</p>

<p>
  <b>Description:</b>
  <%= @reference.description %>
</p>

<p>
  <b>Topic:</b>
  <%= Topic.find(@reference.topic_id).name %>
</p>


<p>
  <b>Tags:</b>
  <%= @reference.tag_list %>
</p>

<%= link_to 'Edit', edit_reference_path(@reference) %> |
<%= link_to 'Back', references_path %>

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<h1>Editing topic</h1>

<%= render 'form' %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<h1>Topics Yo!</h1>
<br />

<% @topics.each do |topic| %>
  <ul>
    <li><%= link_to topic.name, topic %> (<%= topic.references.count %>)</li>
    <!--<td><%= link_to 'Edit', edit_topic_path(topic) %></td>-->
    <!--<td><%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
  </ul>
<% end -%>

<br />

<%= link_to 'New Topic', new_topic_path %>

app/views/topics/new.html.erb
<h1>New topic</h1>

<%= render 'form' %>

<%= link_to 'Back', topics_path %>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>
<h1><%= @topic.name %></h1>
<p>There are <%= @topic.references.size %> Reference documents under this topic.</p>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Tags</th>
    <th>Doc</th>
    <th></th>
  </tr>

<% @topic.references.each do |reference| %>
  <tr>
    <td><%= reference.name %></td>
    <td><%= reference.description %></td>
    <td><%= reference.tag_list %></td>
    <td><%= link_to 'File', reference.doc_url %></td>
    <td><%= link_to 'Show', reference %></td>
  </tr>
<% end %>
</table>


<%= link_to 'Edit', edit_topic_path(@topic) %> |
<%= link_to 'Back', topics_path %>